### ISSUE TITLE
Can you please update,,,  Error : Circular dependency detected while trying to resolve entry 'router'"

### ISSUE THREAD

**Issue by sarelvdm** [fabricelepro/slim-laravel#1]
Fix for the version php-di/slim-bridge v1.0.3. in Container.php

add...  use Slim\Interfaces\RouterInterface;

change 'router' => get(Slim\Router::class),  to

RouterInterface::class => function (ContainerInterface $container) { return $container->get('router'); },

**Comment by fabriceyopa** [comment]
Okay guy,
I take some time to fixed it
